name: Deploy
on: [ push ]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Install deno
        run:
          curl -fsSL https://deno.land/install.sh | sh && export DENO_INSTALL="/home/runner/.deno" && export PATH="$DENO_INSTALL/bin:$PATH"

      - name: Install pnpm
        run: npm i -g pnpm

      - name: Install dependencies
        run: pnpm i --no-frozen-lockfile

      - name: Generate posts
        run: deno run --unstable-kv --allow-env --allow-net --allow-write --allow-read --quiet bin/generate.ts

      - name: Removing scripts
        run: rm -rf ./bin

      - name: Build Astro
        run: pnpm run build

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: proud-spider-99
          entrypoint: server/entry.mjs
          root: dist